### PR TITLE
Added utilities

### PR DESCRIPTION
**Pull request by mahm0106**

### CODE REVIEW

**Comment by mino0027** [comment]
@ZoeyHashemi may you review the conflict and confirm how to proceed.

Kindly,
Chris

**Comment by ZoeyHashemi** [comment]
Morning, I have a class , I'll do it as soon as I can.

Thank you,
Zoey

________________________________________

**Comment by mino0027** [comment]
No rush!
Thanks for the prompt reply!
I'll look to have my branches submitted for review soon too!

Kindly,

040864887
Chris Minosora
***@***.***
________________________________

**Review by ZoeyHashemi — APPROVED** [review]
Looks Good, Thank you

**Pull request merged**
